package presentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by MAX on 15/12/2015.
 */
public class JugarMaquina extends JFrame {
  private JPanel JM;
  private Tauler T;
  private JButton Enrere;

  public JugarMaquina(SeleccionaTauler ant, String idtau) {
    JM = new JPanel(new BorderLayout());
    setContentPane(JM);
    pack();
    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setVisible(true);
    setSize(500, 500);
    setLocationRelativeTo(null);
    T = new Tauler(idtau);
    add(T, BorderLayout.CENTER);
    T.resolTauler(idtau);
    Enrere = new JButton();
    Enrere.setText("Enrere");
    add(Enrere, BorderLayout.SOUTH);
    Enrere.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        ant.setVisible(true);
        setVisible(false);
      }
    });
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    JM = new JPanel();
    JM.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return JM;
  }
}
